;Sample Central Configuration File
[Config]
API_Bearer=eyJhbGciOiJIUzI1NiIsImtpZCI6IkFkbWluQWNjZXNzVG9rZW4iLCJ0eXAiOiJKV1QifQ.eyJzbFN1YnNjcmlwdGlvbklkIjoiMTAyNDU3Iiwic2xSZWdpb24iOiJjYSIsImVtYWlsIjoicmdhdWRldEB2dGV4dnNpLmNvbSIsInNsVG9rZW5WZXIiOiIyLjAiLCJzbENsaWVudCI6InNsdjIiLCJyb2xlIjoiIiwianRpIjoiMnhoTENYZ1RoSDJVcWJhSEtLMllVTWFQTlFhWmt4dS9RUC93Mk1wYVdKVmIrTVpZWWpGYXRNdUl4dlk9IiwidG9rZW5JZCI6Ijk2MjQiLCJleHAiOjE3NzE1NDU2MDAsImlhdCI6MTc0MDA2NDMzMCwiaXNzIjoiU0wuQWRtaW4uQWNjZXNzIiwiYXVkIjoiU0wuVGhpcmRQYXJ0eSJ9.J8qV20WJSLCl_OQKNrqAICdygBVDZop-Aa9aqudQnpA
API_Tenant=https://sl-api-gateway-apim-prod-cae.azure-api.net
API_UserAgent=SpeechLive Helper

[Users]
7777=psp_author3@vtexvsi.com
6666=psp_author1@vtexvsi.com
5555=psp_author9@vtexvsi.com
7878=psp_author1@vtexvsi.com