;Sample Local Configuration File
;Filename will be localconfig.ini
[Config]
Central_Config_UNC=\\localhost\config\centralconfig.ini
Drive_Letter_To_Monitor=none
Delete_Files_After_Upload=true
APP_Identifier=VTEX Development 02
