; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "SpeechLive Upload Helper"
#define MyAppPublisher "VTEX Voice Solutions Inc."
#define MyAppURL "https://www.vtexvsi.com"
#define MyAppExeName "SpeechLiveUploader.exe"
#define MyAppPublishDirectory "C:\Users\Ryan G\Desktop\SpeechLiveHelper\InstallerFiles\"
#define MyAppVersion RemoveFileExt(GetVersionNumbersString(MyAppPublishDirectory+MyAppExeName))
#define MyAppSetupIcon = "sl_favicon.ico"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{997564CA-D217-49DE-A04A-DB275D5917A0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
SetupIconFile=compiler:{#MyAppSetupIcon}
UninstallDisplayIcon="{#MyAppPublishDirectory}{#MyAppSetupIcon}"
DefaultDirName="{autoappdata}\SpeechLive Helper"
DisableProgramGroupPage=yes
DisableDirPage=yes
DisableReadyPage=no
DisableFinishedPage=yes
DisableStartupPrompt=yes
; Remove the following line to run in administrative install mode (install for all users.)
;PrivilegesRequired=lowest
OutputBaseFilename=slhsetup
Compression=lzma2/max 
SolidCompression=yes
WizardStyle=modern
WizardImageFile=compiler:slh_sidebar.bmp
WizardSmallImageFile=compiler:SpeechLive_Helper_Icon.bmp
OutputDir="C:\Users\Ryan G\Desktop\SpeechLiveHelper\Output"
SignTool=NewSignTool $f
ChangesAssociations=no

[Registry]

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
;Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "{#MyAppPublishDirectory}{#MyAppExeName}"; DestDir: "{app}"; Permissions: users-modify; Flags: ignoreversion sign
; NOTE: If you store Archive folder in same folder as source, you must remove the recursesubdirs and createallsubdirs or they will get packaged
Source: "{#MyAppPublishDirectory}*"; DestDir: "{app}"; Permissions: users-modify; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}";


[Run]
Filename: {sys}\sc.exe; Parameters: "create ""SpeechLive Upload Helper"" binPath= ""{app}\SpeechLiveUploader.exe""" ; Flags: runhidden

[UninstallRun]
Filename: {sys}\sc.exe; Parameters: "stop ""SpeechLive Upload Helper""" ; Flags: runhidden
Filename: {sys}\sc.exe; Parameters: "delete ""SpeechLive Upload Helper""" ; Flags: runhidden

